

#...

[custom.jj]
command='''starship-jj --ignore-working-copy starship prompt'''
format = "[$symbol](blue bold) $output "
symbol = "󱗆"
when = "jj root --ignore-working-copy"

[directory]
fish_style_pwd_dir_length = 3
