[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[env]
MISE_NPM_BUN = true

[env._]
file = ".env.json"

[tools]
age = "latest"
aqua = "latest"
bat = "latest"
btop = "latest"
bun = "latest"
cargo-binstall = "latest"
"cargo:atuin" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:gitoxide" = "latest"
"cargo:starship-jj" = "latest"
"cargo:vivid" = "latest"
"cargo:zoxide" = "latest"
chezmoi = "latest"
cmake = "latest"
direnv = "latest"
duf = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
go = "latest"
"go:github.com/umlx5h/gtrash" = "latest"
"go:github.com/wailsapp/wails/v2/cmd/wails" = "latest"
java = "latest"
jj = "latest"
lsd = "latest"
node = "24"
"npm:oclif" = "latest"
"npm:porffor" = "latest"
pipx = "latest"
"pipx:trash-cli" = "latest"
pixi = "latest"
pnpm = "10.10"
python = "3.12.11"
rust = "nightly"
sops = "latest"
starship = "latest"
ubi = "latest"
"ubi:abishekvashok/cmatrix" = "latest"
"ubi:da-luce/astroterm" = "latest"
uv = "latest"
vivid = "latest"
wasmtime = "latest"
yarn = "latest"
yazi = "latest"
zig = "latest"
